-- MySQL Script generated by MySQL Workbench
-- 12/04/15 12:45:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema williams
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema williams
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `williams` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `williams` ;

-- -----------------------------------------------------
-- Table `williams`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `williams`.`Usuario` (
  `Clave` VARCHAR(16) NOT NULL COMMENT '',
  `Nombre` VARCHAR(22) NOT NULL COMMENT '',
  `App` VARCHAR(22) NOT NULL COMMENT '',
  `Apm` VARCHAR(22) NOT NULL COMMENT '',
  `TipoUsu` INT NOT NULL COMMENT '',
  `Nick` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`Nick`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `williams`.`Terapeuta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `williams`.`Terapeuta` (
  `Cedula` VARCHAR(45) NOT NULL COMMENT '',
  `Nick` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`Nick`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `williams`.`Tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `williams`.`Tutor` (
  `Calle` VARCHAR(25) NOT NULL COMMENT '',
  `NumeroEx` INT NOT NULL COMMENT '',
  `NumeroIn` INT NOT NULL COMMENT '',
  `CodigoP` INT NOT NULL COMMENT '',
  `Delegacion` VARCHAR(25) NOT NULL COMMENT '',
  `Ciudad` VARCHAR(25) NOT NULL COMMENT '',
  `Telef` INT NOT NULL COMMENT '',
  `Nick` VARCHAR(45) NOT NULL COMMENT '',
  `Relacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nick`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `williams`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `williams`.`Paciente` (
  `Edad` INT NOT NULL COMMENT '',
  `Sexo` TINYINT(1) NOT NULL COMMENT '',
  `FNac` VARCHAR(11) NOT NULL COMMENT '',
  `Escolaridad` VARCHAR(30) NOT NULL COMMENT '',
  `Lateralidad` INT NOT NULL COMMENT '',
  `Nick` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`Nick`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `williams`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `williams`.`Administrador` (
  `Nick` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`Nick`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `williams`.`Sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `williams`.`Sesiones` (
  `Fecha` VARCHAR(11) NOT NULL COMMENT '',
  `Hora` VARCHAR(11) NOT NULL COMMENT '',
  `Cedula` VARCHAR(45) NOT NULL COMMENT '',
  `idSesion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`idSesion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `williams`.`SesionT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `williams`.`SesionT` (
  `Estudios` VARCHAR(120) NOT NULL COMMENT '',
  `Diagnosticos` VARCHAR(120) NOT NULL COMMENT '',
  `Observaciones` VARCHAR(120) NOT NULL COMMENT '',
  `idSest` INT NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`idSest`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
